name: Run Linting
on:
  - push
jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11
      - name: Setup project
        run: make setup
        env:
          POETRY_VIRTUALENVS_CREATE: "false"
      - uses: pre-commit/action@v3.0.0
