name: Unit Test Python
on:
  - push
jobs:
  unit-test-python:
    name: Unit Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.8
          cache: "pip"
      - name: Setup project
        run: make setup
        env:
          POETRY_VIRTUALENVS_CREATE: "false"
      - uses: pre-commit/action@v3.0.0
