name: Unit Test Python
on:
  - push
jobs:
  unit-test-python:
    name: Unit Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11
      - name: KinD (Kubernetes in Docker) Action
        with:
          skipClusterCreation: true
        uses: engineerd/setup-kind@v0.5.0
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
      - name: Run Python Unit Tests
        run: make test-ci
