name: Unit Test Python
on:
  - push
jobs:
  unit-test-python:
    name: Unit Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.10.8
      - name: Run Python Unit Tests
        run: make test-ci
